# Generated by Django 6.0.3 on 2026-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Untitled', max_length=200)),
                ('autor', models.CharField(default='Anonymous', max_length=200)),
                ('data_criacao', models.DateTimeField(verbose_name='Criado em ')),
                ('qtdObjetos', models.IntegerField(default=0)),
                ('qtdAlfabetos', models.IntegerField(default=0)),
                ('qtdFontes', models.IntegerField(default=0)),
                ('exposto', models.BooleanField(default=False)),
            ],
        ),
    ]
