# Generated by Django 6.0.3 on 2026-03-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagem',
            new_name='Imagens',
        ),
    ]
