# Generated by Django 6.0.3 on 2026-03-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0002_rename_imagem_imagens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagens',
            new_name='Imagem',
        ),
    ]
