# Generated by Django 6.0.3 on 2026-03-22 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0003_rename_imagens_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em '),
        ),
    ]
