# Generated by Django 6.0.3 on 2026-03-23 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0004_imagem_estado_alter_imagem_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='imagem',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado em '),
        ),
        migrations.AddField(
            model_name='imagem',
            name='data_julgamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagem',
            name='paraAprovar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagem',
            name='qtdLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagem',
            name='rejeitado',
            field=models.BooleanField(default=False),
        ),
    ]
