# Generated by Django 6.0.3 on 2026-03-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0005_remove_imagem_data_criacao_imagem_data_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('moderador', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='imagem',
            name='autor',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='titulo',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
