# Generated by Django 6.0.3 on 2026-03-26 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0006_usuario_alter_imagem_autor_alter_imagem_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='data_envio',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='qtdLikes',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='data_julgamento',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='paraAprovar',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='exposto',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='rejeitado',
        ),
        migrations.CreateModel(
            name='userImage',
            fields=[
                ('imagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pixtar.imagem')),
                ('userId', models.IntegerField()),
            ],
            bases=('pixtar.imagem',),
        ),
        migrations.CreateModel(
            name='sharedImage',
            fields=[
                ('imagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pixtar.imagem')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(default='Untitled', max_length=50)),
                ('autor', models.CharField(default='Anonymous', max_length=50)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado em ')),
                ('paraAprovar', models.BooleanField(default=False)),
                ('rejeitado', models.BooleanField(default=False)),
                ('data_julgamento', models.DateTimeField(blank=True, null=True)),
                ('exposto', models.BooleanField(default=False)),
                ('qtdLikes', models.IntegerField(default=0)),
            ],
            bases=('pixtar.imagem',),
        ),
    ]
