# Generated by Django 6.0.3 on 2026-03-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0007_remove_imagem_titulo_remove_imagem_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='qtdCores',
            field=models.IntegerField(default=0),
        ),
    ]
