# Generated by Django 6.0.3 on 2026-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0008_imagem_qtdcores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedimage',
            name='autor',
            field=models.CharField(default='Anonymous', max_length=35),
        ),
        migrations.AlterField(
            model_name='sharedimage',
            name='titulo',
            field=models.CharField(default='Untitled', max_length=35),
        ),
    ]
