# Generated by Django 6.0.3 on 2026-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0009_alter_sharedimage_autor_alter_sharedimage_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedimage',
            name='paraAprovar',
            field=models.BooleanField(default=True),
        ),
    ]
