# Generated by Django 6.0.3 on 2026-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0010_alter_sharedimage_paraaprovar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedimage',
            name='julgado_por',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
