# Generated by Django 6.0.3 on 2026-04-19 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0011_sharedimage_julgado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedimage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likedImages', to=settings.AUTH_USER_MODEL),
        ),
    ]
