# Generated by Django 6.0.3 on 2026-04-20 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0013_remove_sharedimage_userid_sharedimage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eraser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastErase', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='sharedimage',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likedImages', to=settings.AUTH_USER_MODEL),
        ),
    ]
