# Generated by Django 6.0.3 on 2026-04-27 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0014_eraser_delete_usuario_alter_sharedimage_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedimage',
            name='autor',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharedimage',
            name='julgado_por',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='sharedimage',
            name='titulo',
            field=models.CharField(default='Untitled', max_length=15),
        ),
        migrations.AlterField(
            model_name='sharedimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
