# Generated by Django 6.0.3 on 2026-04-29 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0015_alter_sharedimage_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='userId',
        ),
        migrations.AddField(
            model_name='userimage',
            name='date_saved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedimage',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='likedImages', to=settings.AUTH_USER_MODEL),
        ),
    ]
