# Generated by Django 6.0.3 on 2026-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0016_remove_userimage_userid_userimage_date_saved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModPerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_moderate', 'Can moderate')],
            },
        ),
    ]
