# Generated by Django 6.0.3 on 2026-05-09 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0017_modperms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedimage',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likedImages', to=settings.AUTH_USER_MODEL),
        ),
    ]
