# Generated by Django 6.0.3 on 2026-05-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0018_alter_sharedimage_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modperms',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_moderate', 'Can moderate')]},
        ),
    ]
