# Generated by Django 6.0.3 on 2026-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0019_alter_modperms_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedimage',
            name='titulo',
            field=models.CharField(default='Untitled', max_length=35),
        ),
    ]
