# Generated by Django 6.0.3 on 2026-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixtar', '0020_alter_sharedimage_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedimage',
            name='titulo',
            field=models.CharField(default='Untitled', max_length=25),
        ),
    ]
